name: unoquide
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scroll_navigation: ^1.3.2
  flutter_cached_pdfview: ^0.4.1
  youtube_player_iframe: ^4.0.1
  fluttertoast: ^8.1.2
  url_launcher: ^6.1.7
  http: ^0.13.5
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.16
  blur: ^3.1.0
  fwfh_webview: ^0.7.0+1
  table_calendar: ^3.0.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/Icons/
    - assets/Images/
    - assets/Images/Courses/
    - assets/Images/AudioVisuals/
    - assets/Images/EmotionalIntelligence/
    - assets/Images/Stats/
    - assets/Images/Connect/

    - assets/Images/Authentication/
    - assets/Images/Games/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/raleway.ttf
          weight: 900
    - family: GTN
      fonts:
        - asset: fonts/gtn.ttf